name: flutter_hybrid_template
description: A hybrid Flutter app for Mr Ahmed Gamal.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # حدثنا المحرك هنا عشان يدعم أحدث المكتبات

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0 # نسخة أحدث وأسرع
  onesignal_flutter: ^5.2.2    # مكتبة الإشعارات الفورية

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
